// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTGlzLD4cLDy3auml9-06P2ugi51Na58Y',
    appId: '1:381911007614:web:301090a6bba5deadfb332f',
    messagingSenderId: '381911007614',
    projectId: 'task-management-app-f9f98',
    authDomain: 'task-management-app-f9f98.firebaseapp.com',
    storageBucket: 'task-management-app-f9f98.firebasestorage.app',
    measurementId: 'G-93460JHZC9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCWaYP-P3zHujbRpcz-AaMubAA2uAL5AA',
    appId: '1:381911007614:android:e730cc554ed963e3fb332f',
    messagingSenderId: '381911007614',
    projectId: 'task-management-app-f9f98',
    storageBucket: 'task-management-app-f9f98.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrztAc7TE_-cyES77eANBc4eRv8t9WGKU',
    appId: '1:381911007614:ios:47e683f5f9e9a9cbfb332f',
    messagingSenderId: '381911007614',
    projectId: 'task-management-app-f9f98',
    storageBucket: 'task-management-app-f9f98.firebasestorage.app',
    iosBundleId: 'com.example.taskManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrztAc7TE_-cyES77eANBc4eRv8t9WGKU',
    appId: '1:381911007614:ios:47e683f5f9e9a9cbfb332f',
    messagingSenderId: '381911007614',
    projectId: 'task-management-app-f9f98',
    storageBucket: 'task-management-app-f9f98.firebasestorage.app',
    iosBundleId: 'com.example.taskManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTGlzLD4cLDy3auml9-06P2ugi51Na58Y',
    appId: '1:381911007614:web:fde35232b4c93897fb332f',
    messagingSenderId: '381911007614',
    projectId: 'task-management-app-f9f98',
    authDomain: 'task-management-app-f9f98.firebaseapp.com',
    storageBucket: 'task-management-app-f9f98.firebasestorage.app',
    measurementId: 'G-NZ0H6GF6V3',
  );
}
