// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTq_9yd_XzOiTFT8lDLx0XiUUijJsj7_0',
    appId: '1:441329109459:web:90d41d53506f1645464726',
    messagingSenderId: '441329109459',
    projectId: 'task-management-app-b3aee',
    authDomain: 'task-management-app-b3aee.firebaseapp.com',
    storageBucket: 'task-management-app-b3aee.appspot.com',
    measurementId: 'G-5YXD1PMTB5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-ESXXkTwWpn3u4_ENu5gsyxxoDJpya00',
    appId: '1:441329109459:android:bed36b82ba47ee5c464726',
    messagingSenderId: '441329109459',
    projectId: 'task-management-app-b3aee',
    storageBucket: 'task-management-app-b3aee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVyT24FeILgKV1n2ozNPnx6-yqYJ2JfcY',
    appId: '1:441329109459:ios:0743220401a0bce0464726',
    messagingSenderId: '441329109459',
    projectId: 'task-management-app-b3aee',
    storageBucket: 'task-management-app-b3aee.appspot.com',
    iosBundleId: 'com.example.taskManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVyT24FeILgKV1n2ozNPnx6-yqYJ2JfcY',
    appId: '1:441329109459:ios:0743220401a0bce0464726',
    messagingSenderId: '441329109459',
    projectId: 'task-management-app-b3aee',
    storageBucket: 'task-management-app-b3aee.appspot.com',
    iosBundleId: 'com.example.taskManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTq_9yd_XzOiTFT8lDLx0XiUUijJsj7_0',
    appId: '1:441329109459:web:7a5c9358df8731a9464726',
    messagingSenderId: '441329109459',
    projectId: 'task-management-app-b3aee',
    authDomain: 'task-management-app-b3aee.firebaseapp.com',
    storageBucket: 'task-management-app-b3aee.appspot.com',
    measurementId: 'G-Z2BY7DTPTG',
  );
}
